services:
  db:
    image: postgres:15
    container_name: booking_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password12839712937812937921
      POSTGRES_DB: booking_db
    ports:
      - "5438:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: